name: Sync Portfolio to AWS S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2  # This matches London, England
        run: |
          # The --delete flag ensures that if you delete a file locally, 
          # it also gets deleted from your S3 bucket.
          aws s3 sync . s3://lorraine-portfolio-2026 --delete --exclude ".git*" --exclude ".github*"
          